### ISSUE TITLE
Create Rouge highlighter for gobstones

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-gobstones-runner#1]

**Comment by flbulgarelli** [comment]
I am testing it right now, and I have found that literals like `Norte` and `Rojo` are informed as `Name.Builtin.Pseudo`, but they should be `Literal`

**Comment by flbulgarelli** [comment]
Also, check this code: 

```
procedure Poner3(color) {
  Poner(color)
  Poner(color)
  Poner(color)
}

program {
  Poner3(Negro)
  Poner3(Rojo)
}
```

`color` and `Poner3` are not being colored, so I assume we are missing support for arguments and procedures.

**Comment by flbulgarelli** [comment]
Numeric literals are also being recognized as `Name.Builtin.Pseudo` instead of `Literal.Number`.

See https://github.com/jneen/rouge/wiki/List-of-tokens

**Comment by Charlyzzz** [comment]
They are being categorized as Text because coloring parameters would require to keep semanthical scopes of declarations.

The only thing I can come up with is highlighting parameters and local variables indistinctly

**Comment by flbulgarelli** [comment]
> The only thing I can come up with is highlighting parameters and local variables indistinctly

It works for me :+1:  Actually, in the new theme I added to laboratory, I am using the same color for both, since many rouge parsers have similar problems and inconsistencies with ACE editor.

**Comment by flbulgarelli** [comment]
Done
