### ISSUE TITLE
Fix boards scaling glitches

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-gobstones-runner#104]
See https://github.com/gobstones/gs-board/issues/17

We should replicate https://github.com/gobstones/gobstones-web/commit/da881184e4845efbd0baf08ed3e587fd1e69f6be in our code. 

```
<gs-attire attire-url="https://gist.githubusercontent.com/rodri042/17b3d952934b64e6ce9ac19334500d92/raw/ef5fbd2b6c618a01b8bde45a144e2a7a7a3b49ef/attire.json"></gs-attire>```

**Comment by rodri042** [comment]
We decided not to implement this because it's a Chrome-only issue and all the current attires fix it using borders
