### ISSUE TITLE
Reduce response size

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-gobstones-runner#11]
Currently each runner response is ~250KB. We should solve this by removing the polymer JS and configuring it from office as a workaround.

**Comment by flbulgarelli** [comment]
Perhaps we could make this configurable.

**Comment by rodri042** [comment]
This is fixed with https://github.com/mumuki/mumuki-laboratory/commit/9f5b89e1c14dddf98d6ab1131a0581f186df57a7

Closing.
