### ISSUE TITLE
Attires button is always being displayed

### ISSUE THREAD

**Issue by luchotc** [mumuki/mumuki-gobstones-runner#119]
If the boards doesn't have an attire, we shouldn't display the button.
@rodri042 Could you provide a method in gs-board to check this?

**Comment by luchotc** [comment]
@rodri042 Or just guide me what should I ask for to be sure that there isn't any attire defined.
Something like this is enough?

`typeof GobstonesBoard != 'undefined' and not GobstonesBoard.defaultAttire and @noAttire`

**Comment by rodri042** [comment]
I think you can ask directly if the board has an attire property. if
(board.attire) {...}

**Comment by luchotc** [comment]
Ok, but in this scenario we're assuming that **a board will always start with the attire on**, right?
Because in a context where a board starts without an attire but there is one available, board.attire will be false as well, right?

**Comment by rodri042** [comment]
If there was a default attire, this method (
https://github.com/gobstones/gs-board/blob/master/src/components/gs-board/script.coffee#L242)
would assign it, so the 'attire' property would be consistent in all cases
