### ISSUE TITLE
Solo ocultar el cabezal en el tablero esperado, pero no en el obtenido (en ejercicios donde no se chequea)

### ISSUE THREAD

**Issue by julian-berbel** [mumuki/mumuki-gobstones-runner#131]
No se muestra el cabezal en ejercicios en ingles sin check_head_position

**Comment by rodri042** [comment]
Eso fue implementado en https://github.com/mumuki/mumuki-laboratory/issues/1051

Lo que hablamos recién fue hacer que solo oculte el cabezal en el "esperado" pero que lo siga mostrando en el "obtenido"

**Comment by flbulgarelli** [comment]
Nice! This was original intention of referenced issue...

> https://github.com/mumuki/mumuki-laboratory/issues/1051#issuecomment-394521774
> This issue is about not showing the head in `final_state`  board 

...but it looks like that I missed it when I merged @rodri042's PR :stuck_out_tongue:
