### ISSUE TITLE
Support interactive programs in Kids mode

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-gobstones-runner#135]

**Comment by luchotc** [comment]
The layout for interactive programs is yet to be defined. 
It can be done by having two modes (editor and playground, for example) that the kids can alternate or by keeping a similar layout as the current one but with only one board for the kids to test they solution.

If we decide to use the second option, we'll need to find a way to keep the interactive program synced with the student current solution or design a better layout as it will be bloated with different buttons.

**Comment by luchotc** [comment]
One of the challenges we've found is that on mobile devices we can't rely on keyboards.
We decided to use gestures instead of arrows and provide a mini-keyboard in the UI just with the necessary keys.
Although Gobstones allows to define a complex binding (like CTRL + Shift + A), I'm assuming that we aren't going to use them and only limit the keyboard to space, backspace and letters. Is this right @NadiaFinzi ?

**Comment by luchotc** [comment]
Also we need to define details in the layout:

What button are we using to change from playground to editor and where are we going to place it?

Should we keep the same submit button? Should it be present in both layouts? Does it make sense to be able to submit the solution while on playground layout? 

After a successful solution is submitted, should we always display the playground mode for the kids to test their solution? If the solution is not correct, should we always display the editor mode and show the errors like we do in non-interactive kids exercises?

We decided not to show a corollary in interactive exercises. We'll just show the playground mode and when the kids finish playing with it, they can go to the next exercise. Which button are we using for this? Where are we placing it?

**Comment by luchotc** [comment]
There are also some technical details to take into account.
We should support "interactive tests" where we only check the expectations and the validity of the syntax. It isn't enough to just execute the code client side, as we need to persist the failed status in the server.

**Comment by flbulgarelli** [comment]
> There are also some technical details to take into account.
We should support "interactive tests" where we only check the expectations and the validity of the syntax. It isn't enough to just execute the code client side, as we need to persist the failed status in the server.

I agree, but please remember that it should not be necessary to have tests, since mumukit allows that. 

However, we do need some special support since: 

* we still need to provide an initial board, and we normally use that using tests
* ~we still want to check that the program types~. This is not possible without actually executing the program since gobstones is dynamically typed

**Comment by luchotc** [comment]
Minuta de reunión del día de hoy con @flbulgarelli @nadiafinzi @cucusita @rgonzalezt:

### Disposición del layout:

**Modo editor**: Igual que hoy en día, pero con un solo tablero (el inicial) y un teclado en lugar del tablero final.

**Modo juego**: Misma disposición del modo editor, pero el lienzo sin toolbox, lo cual le permite ganar ancho a la parte del tablero. Además @cucusita sugirió cambiar el texto del personaje y la animación del mismo.

### Otras consideraciones del layout 

El teclado debe estar siempre disponible incluso en dispositivos de escritorios, por consistencia visual y para fomentar el uso del mismo. 
El switch de vestimentas se mantiene.

### Flujo:

Se comienza en modo editor. Con un botón a definir (el que hoy en día es el de play) se pasa a modo juego si la solución _compila_. A su vez se envía al servidor la solución, pero visualmente no se muestra nada. 
Desde el modo de juego se puede regresar al modo editor de dos maneras: 
1) Deteniendo la ejecución (con ícono y ubicación del botón a definir). Esta opción simplemente reinicia el tablero y regresa a modo edición.
2) "Enviando" la solución (con ícono y ubicación del botón a definir). Esta opción reinicia el tablero y a su vez da feedback en base a la solución enviada previamente. En caso de fallar, se muestran los errores. En caso de éxito, se muestra corolario (finalmente con este flujo se decidió continuar mostrándolo). 

**Justificación de las decisiones acerca del flujo:** 

1) Queremos fomentar el juego. No queremos que envien la solución sin probarla.
2) Queremos mantener el flujo simple y no introducir demasiados caminos posibles.
3) Minimizar envios al servidor.

### Posibles botones (a terminar de definir):

Separar el boton de stop en 2 íconos. Se van a mantener dentro del lienzo para reforzar la idea de que se está validando el código y no el juego. 
Queremos evitar que se confundan el boton de play actual con el de antes, así que o lo eliminamos o utilizamos uno parecido.
