### ISSUE TITLE
Los bloques de procedimientos y funciones con parámetros del extra code aparecen sin parámetros

### ISSUE THREAD

**Issue by NadiaFinzi** [mumuki/mumuki-gobstones-runner#137]
Al crear procedimientos o funciones con parámetros en el extra code, aparecen los respectivos bloques en el toolbox sin los parámetros. 

![image](https://user-images.githubusercontent.com/7552150/51336214-c07c4e80-1a62-11e9-91da-61d6af99ec30.png)

@flbulgarelli @julian-berbel

**Comment by rodri042** [comment]
Los nombres de los procedimientos tienen que tener un guión bajo por cada parámetro, para decirle en dónde tienen que estar los agujeros. Por ejemplo **ServirMerienda2** tendría que llamarse, por ejemplo, **Servir _ meriendas en _**.

Cierro el issue. Si así tampoco funciona, volvelo a abrir nomás.
