### ISSUE TITLE
The error balloon is wrong positioned in the Z axis

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-gobstones-runner#139]
See https://github.com/mumuki/mumuki-gobstones-runner/issues/138#issuecomment-458151718

**Comment by rodri042** [comment]
Hey,
That's not happening with the current code, nor inside primaria.mumuki.io:

![screenshot2](https://user-images.githubusercontent.com/1631752/52752470-a5551e00-2fd1-11e9-8c6c-9aba44413f86.png)

**Comment by flbulgarelli** [comment]
Hmm, this is actually happening to me on primaria.mumuki.io: 

![image](https://user-images.githubusercontent.com/677436/52791771-7fb72b80-3048-11e9-8f58-fadf7bae08cd.png)

**Comment by flbulgarelli** [comment]
This occurs both in Firefox and Chrome: 

![image](https://user-images.githubusercontent.com/677436/52791861-b55c1480-3048-11e9-97b6-5714773f8d20.png)

**Comment by rodri042** [comment]
Hmm...

But there's no z axis problem there, the compass' text is over the error bubble. This is your screenshot with zoom:
![screenshot8](https://user-images.githubusercontent.com/1631752/52804279-a1bda780-3062-11e9-9675-8e5e65f255f2.png)

**Comment by flbulgarelli** [comment]
You are totally right!! 

Dismiss my comments please
