### ISSUE TITLE
Gobstones ast is not being generated correctly

### ISSUE THREAD

**Issue by luchotc** [mumuki/mumuki-gobstones-runner#157]
For example [this exercise](https://mumuki.io/primaria.staging/exercises/7287-semiya-agua-para-mi-semiya)'s default content generates an "Other" tag in the missing or (||) condition. A similar problem is happening in exercises 5, 6 & 8 of this guide. It would be nice to ensure that at least every default code's ast is generated correctly to avoid a "free" passed result.

**Comment by rodri042** [comment]
I've moved the last part of this issue ("[This exercise](https://mumuki.io/primaria.staging/exercises/7280-semiya-sembrando-el-caos) works ok. When trying to submit the first time fails (like it should), but the problem is that the error is not visible and blockly isn't scrolling to the error.") to https://github.com/mumuki/mumuki-gobstones-runner/issues/161

**Comment by rodri042** [comment]
Decidimos con @luchotc arreglar el tag `Other` de mulang (que estaba mal) en `gobstones-cli#3.2.1`. Eso soluciona el caso en el que alumnos manden como solución un if por ejemplo con la expresión "o bien" sin completar.

Para el default content lo mejor es que el equipo de contenido agregue los tags "COMPLETAR" (en la categoría Auxiliares Docente) en todos los bloques a rellenar por los alumnos!

**Comment by flbulgarelli** [comment]
@luchotc can we close this? Is something still missing?

**Comment by luchotc** [comment]
@flbulgarelli  @rodri042 We still haven't integrated this one. And the main problem is that it is built on top of gobstones-cli which is bugged right now (the issue with the reorder).
Also, the commit updating the version to 3.2.1 in gobstones-cli wasn't pushed.
We could wait till that issue is fixed and release 3.3.0 with both features, or release it now without including the buggy fix.

**Comment by flbulgarelli** [comment]
> We could wait till that issue is fixed and release 3.3.0 with both features, or release it now without including the buggy fix.

Perhaps we should release it without the buggy fix

**Comment by luchotc** [comment]
I'll close this one and add a specific issue in gobstones-cli regarding this.
