### ISSUE TITLE
En tests con múltiples casos toma solo el primero

### ISSUE THREAD

**Issue by Gustrucco** [mumuki/mumuki-gobstones-runner#168]
Ejemplo: https://mumuki.io/pensamiento-computacional-ucema/exercises/7692-desbloqueando-el-codigo-parametros-dibujarlinea3

![image](https://user-images.githubusercontent.com/3957637/57807804-4c179a80-7738-11e9-9c49-4f69c3698156.png)

![image](https://user-images.githubusercontent.com/3957637/57807868-6fdae080-7738-11e9-98a4-cae8b85b6799.png)

**Comment by flbulgarelli** [comment]
El resultado parece correcto, sobre todo si la solución no es correcta.

¿Podrías mostrar el código que enviaste?

**Comment by aguspina** [comment]
Si, el código es:

<img width="564" alt="Screen Shot 2019-05-16 at 11 55 50" src="https://user-images.githubusercontent.com/4105740/57864198-d6600d00-77d1-11e9-8192-7c0626ce68e1.png">

El problema es que, si bien la solución tiene un parámetro `color`, siempre esta tomando como argumento el `Azul`.

**Comment by aguspina** [comment]
De todas formas ayer después del rollback, seguia fallando y solo se arreglo cuando borramos la cache del ejercicio.

**Comment by luchotc** [comment]
Gracias por el feedback! Cree #169 reproduciendo el error. 
Fue introducido por una optimización que hicimos en la ejecución de los batch de gobstones, en la que asumimos que el código de todos los ejemplos será el mismo. Esto es cierto, excepto en el caso de los procedures con argumentos, donde el runner genera a mano una invocación de ese procedure con ese argumento.

**Comment by luchotc** [comment]
It'll be solved by implementing https://github.com/gobstones/gobstones-cli/issues/11

**Comment by rodri042** [comment]
Estoy laburando esto en gobstones-cli. Necesitamos un formato que permita:
- Que el `code` y el `extraCode` solo se compilen una sola vez (porque más no tiene sentido)
- Que algunos ejemplos tengan un `code` custom que pise el del alumno, para manejar el problema de este issue: la invocación a procedimientos/funciones.

Dejo un ejemplo de un batch de ejercicio con procedimientos:
```js
{
  "code": "procedure Meter(color) { Poner(color) }", /* Código del alumno */,
  "extraCode": "function a() { return (2) }", /* Código del docente */,
  "examples": [
    {
      "initialBoard": "GBB 1...", /* Tablero inicial */
      "extraBoard": "GBB 1...", /* Tablero esperado */
      "code": "procedure Meter(color) { Poner(color) } program { Meter(Azul) }" /* Código de invocación */
    },
    {
      "initialBoard": "GBB 1...", /* Tablero inicial */
      "extraBoard": "GBB 1...", /* Tablero esperado */
      "code": "procedure Meter(color) { Poner(color) } program { Meter(Rojo) }" /* Código de invocación */
    }
  ]
}
```

...y de uno mínimo, sin cosas raras:

```js
{
  "code": "procedure Meter(color) { Poner(color) }", /* Código del alumno */,
  "examples": [
    {
      "initialBoard": "GBB 1...", /* Tablero inicial */
      "extraBoard": "GBB 1...", /* Tablero esperado */
    },
    {
      "initialBoard": "GBB 1...", /* Tablero inicial */
      "extraBoard": "GBB 1...", /* Tablero esperado */
    }
  ]
}
```

@flbulgarelli @luchotc revisenlo porfa así estamos todos en la misma página :)

**Comment by luchotc** [comment]
Se me habían ocurrido las dos posibilidades. En su momento propuse [esto](https://github.com/gobstones/gobstones-cli/pull/10#issuecomment-487991741) porque así evitamos enviar información de más (si todos los examples pisan el code, el code del alumno no tiene mucho sentido, además que a veces ya se envía como originalCode). Pero después viendo un poco más el código de como está implementado, veo que son menos cambios y en definitiva termina siendo lo mismo, así que tenés mi :+1: (y el de @flbulgarelli :stuck_out_tongue:).
Sugeriría cambiarle la key de adentro del example de `code` a `runnerGeneratedCode` o algo así, pero el resto está perfecto!

**Comment by luchotc** [comment]
Ojo que igual pensándolo bien, del lado de gobstones-cli te va a ser más sencillo usando la estructura que propuse en ese PR, a menos que no esté viendo algo. Agrupar todos los code iguales en el mismo elemento del array, lo cual te permite hacer de manera transparente: 
batch.map -> compile code && extra -> map.examples -> run example.

De la otra manera tendrías que agrupar en el cli a mano cuales tienen el mismo code y creo que metería un overhead innecesario. 
Igual, quizás haya cosas que no esté viendo. Este es tu terreno @rodri042 :stuck_out_tongue: 

Si no se entiende lo que planteo, pingueame sin problema!

**Comment by rodri042** [comment]
@luchotc 

> (si todos los examples pisan el code, el code del alumno no tiene mucho sentido, además que a veces ya se envía como originalCode)

El originalCode o código del alumno lo necesitamos para generar el AST correcto (si no estaríamos evaluando también el código que generó Mumuki)

> Agrupar todos los code iguales en el mismo elemento del array, lo cual te permite hacer de manera transparente:
batch.map -> compile code && extra -> map.examples -> run example.

Creo que entendí, igual no haría falta hacer eso porque los ejercicios son como el primer ejemplo que pasé (pongámosle A) o como el segundo (B).
- Los ejercicios que comparten código (la mayoría) y tienen distintos examples entran en el B, y necesitan un solo code y muchos tableros.
- Los que usan llamados a funciones/procedimientos (los que se rompieron en este issue) usan el A y necesitan el código original + un código generado por cada example (que siempre es distinto, si no no tendría sentido) (o puede repetirse entre examples pero no nos importa optimizar a tal punto)

En fin, voy a ver cómo sale más fácil y te cuento :P
