### ISSUE TITLE
Toolbox sin categorías

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-gobstones-runner#182]
Para no tener que cambiar los ejercicios existentes, el XML que define el toolbox seguirá siendo [igual que antes](https://raw.githubusercontent.com/MumukiProject/mumuki-guia-gobstones-procedimientos-kids/master/assets/toolbox_1553288414373.xml). Se agrega la posibilidad de especificar un XML sin categorías, para los casos en que no interesan los procedimientos ni funciones primitivas:

```xml
<block type="Poner"></block>
<block type="Sacar"></block>
<block type="Mover"></block>
```

Por el momento, el runner decidirá si mostrar o no las categorías, basado en el layout del ejercicio:
* si el layout es `input_kindergarten`, no se mostrarán;
* en caso contrario, se mostrarán.

**Comment by faloi** [comment]
@flbulgarelli para terminar de definir la estrategia, te pregunto: ¿serviría tener una configuración "global" (por ejercicio) que provoque que el toolbox se aplane, sin importar las categorías que estén definidas?

**Comment by flbulgarelli** [comment]
> @flbulgarelli para terminar de definir la estrategia, te pregunto: ¿serviría tener una configuración "global" (por ejercicio) que provoque que el toolbox se aplane, sin importar las categorías que estén definidas?

¡Suena bien!

**Comment by faloi** [comment]
![toolbox-without-categories](https://user-images.githubusercontent.com/1585835/89951561-08913200-dc02-11ea-95c6-3ba0058a275e.gif)
