### ISSUE TITLE
Opción para limitar la cantidad de bloques

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-gobstones-runner#185]
# :microscope: Estudio de factibilidad

Blockly lo soporta out-of-the-box de manera _global_ o _por instancia_, mediante las opciones `maxBlocks` y `maxInstances` respectivamente. Hay un ejemplo de la versión global [en su sitio](https://blockly-demo.appspot.com/static/demos/maxBlocks/index.html):

![image](https://user-images.githubusercontent.com/1585835/89562648-a8a91e80-d7f0-11ea-8d14-8fb70be48c4a.png)

Lo que hace Blockly cuando se llega al límite es deshabilitar todos los bloques del toolbox. Si se quiere agregar otro tipo de feedback visual hay que implementarlo a mano con un `changeListener`. El ejemplo de la imagen está hecho así:
 
```js
var demoWorkspace = Blockly.inject('blocklyDiv', {
  media: '../../media/',
  maxBlocks: 5,
  toolbox: document.getElementById('toolbox'),
});

function onchange(event) {
  document.getElementById(
    'capacity'
  ).textContent = demoWorkspace.remainingCapacity();
}

demoWorkspace.addChangeListener(onchange);
onchange();
```

# :spiral_notepad: Cambios propuestos

Exponer dos properties nuevas:
* `maxBlocks`: que configure este valor en Blockly,
* `onBlocksChanged(action)`: que permita configurar un listener. El listener debería recibir por parámetro la cantidad de bloques que quedan disponibles.

**Comment by faloi** [comment]
@flbulgarelli habría que trabajar un poco más en cómo sería el feedback visual de esta funcionalidad. Por defecto lo único que hace es deshabilitar los bloques (el mensajito de _You have X block(s) left_ es custom, no viene con Blockly).

**Comment by faloi** [comment]
Volver a revisar si Blockly no soporta una validación por tipo de bloque.

**Comment by asanzo** [comment]
¿Es esto parte de una estrategia didáctica para enseñar repetición o procedimientos?

Si es así, pueden ver cómo funciona en https://lightbot.com/flash.html en particular para los procedimientos.

La crítica que siempre tuvimos a esto fue que:
- Sirve para tryhardear y eventualmente aprender la _mecánica_ de los procedimientos. :+1: 
- Es necesario complementarla con una charleta de la visión de los procedimientos como reificadores de las partes de tu estrategia.
