### ISSUE TITLE
Definición de procedimientos y funciones primitivas con íconos

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-gobstones-runner#186]
La idea es poder asignarle a nivel contenidista un ícono tanto a bloques nativos Gobstones (opcional) como procedimientos y funciones primitivas definidas por el usuario (fundamental). 

# :eyes: Prototipo

![image](https://user-images.githubusercontent.com/1585835/90550017-ba31e500-e165-11ea-84fc-22214f9703ad.png)

# :repeat: Opciones para la repetición simple

**Importante:** los colores de las capturas que hay debajo son los que por defecto tiene el componente de bloques, pero en la versión final serán los de Mumuki (como se ve en la captura de arriba). Observar solamente el estilo de encastre del número con el bloque repetir.

### Input inline, con íconos de 32px y 64px

Notar que el "agujero" nunca cambia de tamaño y termina quedando chico en comparación con el bloque que se va a encastrar allí. Una vez encastrado se expande, como se ve en la primera imagen. 

![image](https://user-images.githubusercontent.com/1585835/90696317-6bae4480-e252-11ea-9f6e-fdbd81f26339.png) ![image](https://user-images.githubusercontent.com/1585835/91077080-da0a5280-e616-11ea-95cb-e6f1c82eb2ed.png) ![image](https://user-images.githubusercontent.com/1585835/91077180-01611f80-e617-11ea-95d2-649abddc8901.png)

### Input externo, arriba, con íconos de 32px y 64 px

En este caso, lo que no cambia de tamaño es la muesca donde va la expresión numérica, que puede resultar muy pequeña en relación al tamaño del bloque. Cuando se encastra queda perfecto el tamaño.

![image](https://user-images.githubusercontent.com/1585835/90697017-d613b480-e253-11ea-8b9e-d5504a55ca59.png) ![image](https://user-images.githubusercontent.com/1585835/91915964-4a0d7e00-ec92-11ea-8279-7c7e9c44c1c3.png) ![image](https://user-images.githubusercontent.com/1585835/91915908-25190b00-ec92-11ea-948b-a2e6ec4072c4.png)

### Input externo, arriba (no alineado)

![image](https://user-images.githubusercontent.com/1585835/90696253-4e797600-e252-11ea-8ba1-00cfed759129.png)

### Input externo, abajo

![image](https://user-images.githubusercontent.com/1585835/90696748-3b1ada80-e253-11ea-9d96-f9a5a268ee20.png)

**Comment by faloi** [comment]
Probablemente haya que incluir una configuración para modificar la altura de los bloques, así el ícono se ve más grande.

**Comment by faloi** [comment]
@flbulgarelli viendo un poco cómo funciona todo esto, pienso que lo más sencillo es que los íconos para los bloques nativos queden definidos dentro de `gs-element-blockly`. Para procedimientos/funciones primitivas irían como una URL (o base64) dentro del XML que define le contenidista. Les quedaría a ustedes pensar cómo incluir esa property en el XML, podría ser a mano o con algo que desarrollen en biblioteca.

¿Cómo la ves?

**Comment by faloi** [comment]
>  Vamos por la opción 1. Sería ideal además contar con alguna forma programática de definir el tamaño de los íconos externamente.

Agregué un [comentario en el código](https://github.com/mumuki/mumuki-gobstones-runner/pull/191/files#diff-76578cf8fe2362b8bed1ec5508daba9eR124) de cómo hacer esto.

**Comment by asanzo** [comment]
> Notar que el "agujero" nunca cambia de tamaño y termina quedando chico en comparación con el bloque que se va a encastrar allí. Una vez encastrado se expande, como se ve en la primera imagen.

Sobre esto, quizás quieren jugar con el zoom en lugar que con el tamaño de los íconos.

Sobre el ícono ![Selección_999(524)](https://user-images.githubusercontent.com/5421992/91351409-a538ff80-e7be-11ea-9a3a-87744cef6617.png) me lo imagino a Fidel diciendo que es "procedimental" o "poco declarativo", porque da idea de control de flujo. Ahora mismo lo único que se me ocurre declarativo es un "por", tipo X 3 , o algo así. Pero puede quedar este comentario en el limbo para siempre.

De hecho, tengo un comment más interesante para hacer al respecto, que es didáctico: no es simple explicar, al hablar de condiciones borde, que el orden de las cosas dentro del repeat importa.
Por ejemplo, si tenés que comer todas las manzanas de una fila de 6 casilleros (y hay manzanas en todos los casilleros, y estás parado en el primero). 

Esto está mal:
```
Repetir 6
   comer
   avanzar
```

Y es relativamente fácil explicar que se tiene que mover 5 veces. Pero lo que no es sencillo de explicar es por qué estas dos están bien:


```
Repetir 5
   comer
   avanzar
comer
```


```
comer
Repetir 5
   avanzar
   comer
```

Y estas están mal:


```
comer
Repetir 5
   comer
   avanzar
```


```
Repetir 5
   avanzar
   comer
comer
```

Usualmente terminan entendiendo soles, con prueba y error. Lo cual no es malo, pero si se me traba alguien no sé cómo lo explico: le digo que el repetir "pega 5 veces ese código", y analizamos el programa equivalente? o le digo "mirá que al _entrar_ al repetir lo primero que hace es lo de arriba".

Es loco que muchas veces ese orden a elles no les importe (es un error común) porque ven a la repetición como algo más coloquial, más declarativo. (por eso el error con el 6 del ppio).

En fin, voy a tirarme pedos mentales a otro lado.
