### ISSUE TITLE
New gobstones runner 

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-gobstones-runner#2]
We need a new gobstones runners that is a complete rewrite of the original https://github.com/mumuki/mumuki-xgobstones-runner. 

It should: 

* be a complete rewrite, that drops all legacy features of the xgobstones-server
* be based on gobstones-web and https://github.com/gobstones/gs-weblang-core. 
* be similar to https://github.com/mumuki/mumuki-qsim-runner, since QSim and Gobstones, despite they obvious differences, are very similar in the way the work: text input with configurable settings, HTML output.

**Comment by flbulgarelli** [comment]
@faloi @Charlyzzz @rodri042 when developing both qsim and gobstones runners, we should always discuss among us how to implement it

**Comment by rodri042** [comment]
@flbulgarelli can you check my permissions for this repository?

**Comment by faloi** [comment]
@rodri042 done!

**Comment by rodri042** [comment]
Hola!
Les dejo algunas preguntas sobre esto:

Por ahora estoy siguiendo el formato de yml que se vino usando hasta ahora, porque me deja ver rápido si lo que hago está bien o no al probarlo con atheneum y la guía de fundamentos. Aparte creo que queríamos mantenerlo retrocompatible. Esto es:

```yml
show_initial_board: false
check_header_position: true

examples:
 - initial_board: |
     GBB/1.0
     size 3 3
     head 0 0
   final_board: |
     GBB/1.0
     size 3 3
     head 0 0"
```

¿Queremos que los tests se sigan escribiendo de esta manera, o hay que soportar otra nueva? En este ejemplo, ¿cómo se escribiría?

------------------------

¿Dónde puedo encontrar el repo de github con esa guía de fundamentos? Quiero ver cómo se escribe cuando se espera un boom y el tipo de error.

------------------------

Ví [acá](https://github.com/mumuki/mumuki-fundamentos-xgobstones-guia-recorridos-listas/blob/5ce9e3515b120d898694cd76f4f7bb4de50381bc/00100_Recorriendo%20una%20lista/test.yml#L4) que se le puede pasar la precondición **arguments** y la postcondición **return**. ¿Esto es exclusivo de xgobstones o también entra en gobstones?.  Si es el último caso, el intérprete tendría que poder informar lo que devuelve una función, dados ciertos argumentos.

**Comment by flbulgarelli** [comment]
Closing. This has already been done.
