### ISSUE TITLE
Error esperable colisión para primer ciclo

### ISSUE THREAD

**Issue by rgonzalezt** [mumuki/mumuki-gobstones-runner#206]
En los ejercicios podemos esperar que el resultado sea un error (y está bien). Para eso hacemos un yaml de este estilo:

```
examples:
 - title: '¡BOOM!'
   initial_board: |
     GBB/1.0
     size 2 2
     cell 1 0 Rojo 1
     cell 1 1 Negro 1
     head 1 1
   error: no_stones
```

Siendo `error: no stones` el error que esperamos que pase. 
Los que hay disponibles actualmente son:

- `no_stones`: This error occurs when a ball is tried to be removed but there were no balls in that cell.
- `out_of_board`: This error occurs when a move is made that falls out of the board.
- `wrong_argument_type`: This error occurs when a function is called with the incorrect type of argument. For example: Mover(Rojo)
- `unassigned_variable`

Para primer ciclo se creó el error de colisión (¡que funciona genial!) pero no tiene ese soporte para los tests que es necesario para los ejercicios que queremos crear.

**Comment by flbulgarelli** [comment]
Respuesta rápida: hoy verifiqué que sí se puede capturar, usando el código especial `boom-called`, lo cual plasmé en este test: https://github.com/mumuki/mumuki-gobstones-runner/commit/c2875b69ea67a78e0bde014e7906edcc141fe361#diff-800588e3890bf8789d164579d3f87b2a5a8ee384fbea341a0e2e84ab52e887aaR835

De todas formas, me anoto documentarlo y en lo posible desacoplarlo de la implementación, dado que ese es un código interno del intérprete y no realmente algo provisto por el runner.
