### ISSUE TITLE
Ensure i18n is working

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-gobstones-runner#27]
In issue https://github.com/mumuki/mumuki-gobstones-runner/issues/24 it looks like i18n is not being properly handled. we should check that.

**Comment by rodri042** [comment]
It's working! I just had to update my dependencies

**Comment by rodri042** [comment]
@flbulgarelli Actually, the functions guide [has the wrong locale](https://github.com/sagrado-corazon-alcal/mumuki-guia-fundamentos-funciones/blob/c4c72de230b2ce90d2e146ef52dcb29af69359d4/meta.yml#L3) (and the old runner was ignoring it)

**Comment by flbulgarelli** [comment]
Awesome!!

**Comment by flbulgarelli** [comment]
> @flbulgarelli Actually, the functions guide has the wrong locale (and the old runner was ignoring it)

Fixed https://github.com/sagrado-corazon-alcal/mumuki-guia-fundamentos-funciones/commit/929f496b3701742401682391a10f987a88a0869f
