### ISSUE TITLE
error: wrong_arguments_type is being ignored

### ISSUE THREAD

**Issue by luchotc** [mumuki/mumuki-gobstones-runner#38]
Possibly related to #37 

### Example

	{
		"content" : "program {\nDibujarLinea3(Este, Verde)\nMover(Este)\nDibujarLinea3(Norte, Rojo)\nMover(Norte)\nDibujarLinea3(Oeste, Negro)\nMover(Oeste)\nDibujarLinea3(Sur, Azul)\n}",
		"test" : "check_head_position: true\n\nexamples:\n - title: '¡BOOM!'\n   initial_board: |\n     GBB/1.0\n     size 3 3\n     head 0 0\n   error: wrong_argument_type",
		"expectations" : [ ],
		"extra" : "procedure DibujarLinea3(color, direccion) {\n  Poner(color)\n  Mover(direccion)\n  Poner(color)\n  Mover(direccion)\n  Poner(color)\n}",
		"language" : "gobstones"
	}

### Result

Los tests results fueron los siguientes:
`
[{:title=>"¡BOOM!", :status=>:failed, :result=>"<style>\n\n  .boards-container {\n    display: inline-flex;\n  }\n\n  .error-text {\n    color: #d9534f;\n  }\n\n  .boom-text {\n    margin-top: 20px;\n  }\n\n  .title {\n    color: #b4bcc2;\n    text-align: left;\n    font-family: Arial, Helvetica, sans-serif;\n    font-size: 9pt;\n  }\n\n  .board {\n    margin: 0 15px;\n  }\n\n</style>\n\n\n  <p class=\"error-text\">\n    The program was expected to fail by <strong>translation missing: en.code_wrong_argument_type</strong>, but it failed by another reason.\n  </p>\n\n\n<div class=\"boards-container\">\n\n  \n\n</div>\n\n\n  <div class=\"boom-text\">\n    <strong>BOOM</strong>\n    <pre>[11:3]: El parámetro #1 de la operación \"Poner\" debería ser de tipo Color pero el argumento es de tipo Dir:Este.</pre>\n  </div>\n\n"}]`

**Comment by rodri042** [comment]
This could be simply fixed by:
- Replacing `wrong_arguments_type` by `primitive-argument-type-mismatch` in the tests
- Adding the conversion to this method: https://github.com/mumuki/mumuki-gobstones-runner/blob/master/lib/checker.rb#L95
