### ISSUE TITLE
Board not in GBB format error

### ISSUE THREAD

**Issue by luchotc** [mumuki/mumuki-gobstones-runner#39]
### Example

``` json

{
		"content" : "procedure SalirDeLineaVerde(direccion) {\nwhile (hayBolitas(Verde)){\nMover(direccion)\n}\n}",
		"test" : "check_head_position: true\n\nsubject: SalirDeLineaVerde\n\nexamples:\n - arguments:\n   - Este\n   initial_board: |\n     GBB/1.0\n     size 5 2\n     cell 0 0 Verde 1\n     cell 1 0 Verde 1\n     cell 2 0 Verde 1\n     head 0 0\n   final_board: |\n     GBB/1.0\n     size 5 2\n     cell 0 0 Verde 1\n     cell 1 0 Verde 1\n     cell 2 0 Verde 1\n     head 3 0\n     \n - arguments:\n   - Sur\n   initial_board: |\n     GBB/1.0\n     size 3 4\n     cell 1 3 Verde 1\n     head 1 3\n   final_board: |\n     size 3 4\n     cell 1 3 Verde 1\n     head 1 2",
		"expectations" : [ ],
		"extra" : "",
		"language" : "gobstones"
}
```

### Result

The variable output in this line: https://github.com/mumuki/mumuki-gobstones-runner/blob/master/lib/expectations_hook.rb#L9 has this value: `{:status=>"all_is_broken_error", :message=>"Something has gone very wrong", :detail=>{}, :moreDetail=>"GBB/1.0: Board not in GBB/1.0 format."}`

**Comment by rodri042** [comment]
The `final_board` has invalid GBB:

`\n     size 3 4\n     cell 1 3 Verde 1\n     head 1 2`

It must contain the `GBB/1.0` string.

**Comment by flbulgarelli** [comment]
OK. It would be nice that the runner completes the failing header, so that we must not change such exercises
