### ISSUE TITLE
Numbers are being compared as Numbers but, apparently, they need to be compared as Strings

### ISSUE THREAD

**Issue by luchotc** [mumuki/mumuki-gobstones-runner#40]
### Example

``` json
	{
		"content" : "function numero(){\nvalor:=cifra()\nMover(Este)\nvalor:=(valor*100)+(cifra()*10)\nMover(Este)\nvalor:=(valor+cifra())\nreturn(valor)\n}",
		"test" : "subject: numero\n\nexamples:\n - initial_board: |\n     GBB/1.0\n     size 3 1\n     cell 0 0 Rojo 1\n     cell 1 0 Rojo 3\n     cell 2 0 Rojo 2\n     head 0 0\n   return: '132'\n\n - initial_board: |\n     GBB/1.0\n     size 3 1\n     cell 0 0 Rojo 6\n     cell 1 0 Rojo 7\n     cell 2 0 Rojo 8\n     head 0 0\n   return: '678'",
		"expectations" : [
			{
				"binding" : "numero",
				"inspection" : "HasVariable"
			},
			{
				"binding" : "numero",
				"inspection" : "HasUsage:cifra"
			}
		],
		"extra" : "function cifra() {\n  return (nroBolitas(Rojo))\n}",
		"language" : "gobstones"
	}
```

### Results

Los tests results fueron: ` [{:title=>"numero() -> 132", :status=>:failed, :result=>"<style>\n\n  .boards-container {\n    display: inline-flex;\n  }\n\n  .error-text {\n    color: #d9534f;\n  }\n\n  .boom-text {\n    margin-top: 20px;\n  }\n\n  .title {\n    color: #b4bcc2;\n    text-align: left;\n    font-family: Arial, Helvetica, sans-serif;\n    font-size: 9pt;\n  }\n\n  .board {\n    margin: 0 15px;\n  }\n\n</style>\n\n\n  <p class=\"error-text\">\n    <strong>132</strong> was expected but <strong>132</strong> was obtained.\n  </p>\n\n\n<div class=\"boards-container\">\n\n  \n    <div class=\"board\">\n      <p class=\"title\">Initial board</p>\n      <p>\n        \n          <gs-board>\n            GBB/1.0\nsize 3 1\ncell 0 0 Rojo 1\ncell 1 0 Rojo 3\ncell 2 0 Rojo 2\nhead 0 0\n\n          </gs-board>\n        \n      </p>\n    </div>\n  \n\n</div>\n\n\n"}, {:title=>"numero() -> 678", :status=>:failed, :result=>"<style>\n\n  .boards-container {\n    display: inline-flex;\n  }\n\n  .error-text {\n    color: #d9534f;\n  }\n\n  .boom-text {\n    margin-top: 20px;\n  }\n\n  .title {\n    color: #b4bcc2;\n    text-align: left;\n    font-family: Arial, Helvetica, sans-serif;\n    font-size: 9pt;\n  }\n\n  .board {\n    margin: 0 15px;\n  }\n\n</style>\n\n\n  <p class=\"error-text\">\n    <strong>678</strong> was expected but <strong>678</strong> was obtained.\n  </p>\n\n\n<div class=\"boards-container\">\n\n  \n    <div class=\"board\">\n      <p class=\"title\">Initial board</p>\n      <p>\n        \n          <gs-board>\n            GBB/1.0\nsize 3 1\ncell 0 0 Rojo 6\ncell 1 0 Rojo 7\ncell 2 0 Rojo 8\nhead 0 0\n\n          </gs-board>\n        \n      </p>\n    </div>\n  \n\n</div>\n\n\n"}]
`

**Comment by rodri042** [comment]
Same as https://github.com/mumuki/mumuki-gobstones-runner/issues/34#issuecomment-360858997
