### ISSUE TITLE
 Board format not being recognized in test

### ISSUE THREAD

**Issue by luchotc** [mumuki/mumuki-gobstones-runner#41]
Possibly related to #37

### Example

``` json
{
		"content" : "function boomBoomKid() {\n  return (unaVariableQueNoExiste)\n}",
		"test" : "subject: boomBoomKid\n\nshow_initial_board: false\n\nexamples:\n - error: unassigned_variable",
		"expectations" : [ ],
		"expected_expectation_results" : [
			{
				"binding" : "program",
				"inspection" : "Not:HasBinding",
				"result" : "passed"
			},
			{
				"binding" : "boomBoomKid",
				"inspection" : "HasBinding",
				"result" : "passed"
			}
		],
		"extra" : "",
		"expected_status" : "passed",
		"language" : "gobstones",
		"guide_slug" : "sagrado-corazon-alcal/mumuki-guia-fundamentos-variables",
		"exercise_id" : 3,
		"name" : "Una nueva especie de BOOM",
		"sent_at" : "2018-01-17T02:50:25.461Z"
}
```

### Result

`{"exit":"errored","out":"<strong>765: unexpected token at 'Some requests of the batch are invalid. The format is: { initialBoard, [extraBoard], code }.\n'</strong>\n<pre>/var/lib/gems/2.3.0/gems/json-2.1.0/lib/json/common.rb:156:in `parse'\n/var/lib/gems/2.3.0/gems/json-2.1.0/lib/json/common.rb:156:in `parse'\n/home/lucho/mumuki/mumuki-gobstones-runner/lib/extensions/string.rb:3:in `parse_as_json'\n/home/lucho/mumuki/mumuki-gobstones-runner/lib/precompile_hook.rb:28:in `post_process_file'\n/var/lib/gems/2.3.0/gems/mumukit-2.19.0/lib/mumukit/templates/file_hook.rb:15:in `run!'\n/home/lucho/mumuki/mumuki-gobstones-runner/lib/precompile_hook.rb:19:in `compile'\n/var/lib/gems/2.3.0/gems/mumukit-2.19.0/lib/mumukit/server/test_server.rb:94:in `preprocess'\n/var/lib/gems/2.3.0/gems/mumukit-2.19.0/lib/mumukit/server/test_server.rb:102:in `respond_to'\n/var/lib/gems/2.3.0/gems/mumukit-2.19.0/lib/mumukit/server/test_server.rb:34:in `test!'` ...

**Comment by rodri042** [comment]
Can you post the request it's being sent to `gobstones-cli`? (https://github.com/mumuki/mumuki-gobstones-runner/blob/master/lib/precompile_hook.rb#L24)
