### ISSUE TITLE
Fix Blockly's assets path

### ISSUE THREAD

**Issue by rodri042** [mumuki/mumuki-gobstones-runner#71]
This is needed for supporting Blockly sounds.
![screenshot80](https://user-images.githubusercontent.com/1631752/37128618-a755d458-2283-11e8-8c34-42beacfd6e5e.png)

If the runner knew its own url, it would be possible to pass the assets path to `<gs-element-blockly />` with the `media` property.

Related to https://github.com/mumuki/mumuki-gobstones-runner/pull/69#issuecomment-370422373

**Comment by luchotc** [comment]
I've opened the issue a while ago in blockly as well: https://github.com/Program-AR/gs-element-blockly/issues/100

**Comment by rodri042** [comment]
I think that this case is more a `mumuki-gobstones-runner` issue. `gs-element-blockly` already supports a `media` string parameter that represents the URL of the `media` folder.

We just need to give blockly the right path to `media` and add it to the assets server.

**Comment by rodri042** [comment]
Fixed!
