### ISSUE TITLE
When closing the modal we should reset the errors present in the blocks as well

### ISSUE THREAD

**Issue by luchotc** [mumuki/mumuki-gobstones-runner#77]
![screenshot-2018-4-3 fundamentos primeros programas - boom - mumuki](https://user-images.githubusercontent.com/11860076/38269933-4d799584-3758-11e8-8bb4-05992a806c33.png)

**Comment by flbulgarelli** [comment]
Please see https://github.com/mumuki/mumuki-laboratory/issues/976

I think is the same issue.

**Comment by luchotc** [comment]
They are not the same but we can merge this two issues into one if you want to.

**Comment by luchotc** [comment]
I'll close this one and add it to mumuki/mumuki-laboratory#976
