### ISSUE TITLE
El globo de texto con el mensaje de error desaparece

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-gobstones-runner#89]
Tras cerrar el popup de resultados en el laboratorio, el globo de diálogo se rompe de la siguiente forma: 

![image](https://user-images.githubusercontent.com/677436/38635968-5436167c-3d9d-11e8-9798-82d905e44a81.png)

**Comment by luchotc** [comment]
This won't be a bug anymore when we get rid of the pop-up :smile:

**Comment by luchotc** [comment]
Fixed in https://github.com/mumuki/mumuki-laboratory/pull/1029
